'use strict';
/* Módulo isolado: não altera index.html, core.js, Store ou Firebase. */
(function(){
 const KEY='CH_DOCUMENTOS';
 const $=id=>document.getElementById(id);
 const money=v=>window.CH?.Utils?.formatCurrency ? CH.Utils.formatCurrency(v) : new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
 const id=()=>window.CH?.Utils?.generateId?.() || ('doc_'+Date.now()+'_'+Math.random().toString(36).slice(2));
 const today=()=>new Date().toLocaleDateString('pt-BR');
 const iso=()=>new Date().toISOString();
 const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
 const save=a=>localStorage.setItem(KEY,JSON.stringify(a.slice(0,500)));
 const estoque=()=>window.CH?.Store?.getEstoque?.()||[];
 const vendas=()=>window.CH?.Store?.getVendas?.()||[];
 function norm(p){return {id:p.id,nome:p.nome||p.descricao||'Produto',preco:Number(p.precoUn??p.precoVenda??p.preco??0),categoria:p.categoria||'',un:p.unidade||p.un||'UN'}}
 function productsHtml(mode){const arr=estoque().map(norm).filter(p=>p.nome); if(!arr.length)return '<div class="empty">Nenhum produto cadastrado no estoque.</div>';return arr.map((p,i)=>`<div class="prod"><div><b>${esc(p.nome)}</b><small>${esc(p.categoria||p.un)} • ${money(p.preco)}</small></div><input class="qty ${mode==='enc'?'enc-q':'orc-q'}" data-id="${esc(p.id)}" type="number" min="0" step="1" value="0"><span>${mode==='enc'?'itens':'qtd.'}</span></div>`).join('')}
 function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function selected(mode){const cls=mode==='enc'?'.enc-q':'.orc-q';const map=new Map(estoque().map(p=>[String(p.id),norm(p)]));return [...document.querySelectorAll(cls)].map(x=>({p:map.get(String(x.dataset.id)),q:Number(x.value)||0})).filter(x=>x.p&&x.q>0)}
 function renderProducts(){ $('encProdutos').innerHTML=productsHtml('enc');$('orcProdutos').innerHTML=productsHtml('orc');calcOrc();}
 function encPreview(items){const title=esc($('encTitulo').value||'OFERTAS CH GELADAS'), msg=esc($('encMensagem').value||''), val=$('encValidade').value;return `<div class="encarte"><div style="grid-column:1/-1;text-align:center"><h1 style="margin:0;font-size:30px;font-weight:900">${title}</h1><p style="margin:6px 0;font-weight:700">${msg}</p>${val?`<span class="tag">Válido até ${new Date(val+'T12:00:00').toLocaleDateString('pt-BR')}</span>`:''}</div>${items.map(x=>`<div class="enc-card"><div class="name">${esc(x.p.nome)}</div><small>${esc(x.p.un)}</small><div class="price">${money(x.p.preco)}</div></div>`).join('')}</div>`}
 function gerarEncarte(){const items=selected('enc');if(!items.length)return alert('Selecione ao menos um produto.');const doc={id:id(),tipo:'encarte',numero:next('ENC'),criadoEm:iso(),data:today(),titulo:$('encTitulo').value,mensagem:$('encMensagem').value,validade:$('encValidade').value,itens:items};push(doc);$('encPreview').innerHTML=encPreview(items);}
 function calcOrc(){const items=selected('orc');const sub=items.reduce((s,x)=>s+x.p.preco*x.q,0),d=Math.min(Number($('orcDesconto').value)||0,sub);$('orcTotal').textContent=money(sub-d);return {items,sub,d,total:sub-d}}
 function orcPreview(doc){return `<h3>ORÇAMENTO ${esc(doc.numero)}</h3><p style="margin:0;color:#6b7280">Emitido em ${esc(doc.data)} • validade ${doc.validade?new Date(doc.validade+'T12:00:00').toLocaleDateString('pt-BR'):'não informada'}</p><p><b>Cliente:</b> ${esc(doc.cliente||'Não informado')}</p><table><thead><tr><th>Produto</th><th>Qtd.</th><th class="right">Unit.</th><th class="right">Total</th></tr></thead><tbody>${doc.itens.map(x=>`<tr><td>${esc(x.p.nome)}</td><td>${x.q}</td><td class="right">${money(x.p.preco)}</td><td class="right">${money(x.p.preco*x.q)}</td></tr>`).join('')}</tbody></table><div class="total"><span>Subtotal ${money(doc.subtotal)}<br>Desconto ${money(doc.desconto)}</span><strong>${money(doc.total)}</strong></div>${doc.obs?`<p><b>Condições:</b> ${esc(doc.obs)}</p>`:''}<p class="hint">Documento de orçamento. Não representa venda e não baixa estoque.</p>`}
 function salvarOrcamento(){const r=calcOrc();if(!r.items.length)return alert('Adicione ao menos um item.');const doc={id:id(),tipo:'orcamento',numero:next('ORC'),criadoEm:iso(),data:today(),cliente:$('orcCliente').value.trim(),validade:$('orcValidade').value,obs:$('orcObs').value.trim(),subtotal:r.sub,desconto:r.d,total:r.total,itens:r.items};push(doc);$('orcPreview').innerHTML=orcPreview(doc);}
 function renderVendas(){const arr=vendas().filter(v=>v&&v.status!=='cancelada').slice(0,100);$('vendasLista').innerHTML=arr.length?arr.map(v=>`<div class="doc"><div><b>${esc(v.id?.slice(-8)||'venda')} • ${esc(v.data||'')}</b><small>${esc(v.operador||'')} • ${esc(v.formaPgto||'')}</small></div><div style="text-align:right"><b>${money(v.total)}</b><br><button class="btn" onclick="documentosService.recibo('${esc(v.id)}')">Ver recibo</button></div></div>`).join(''):'<div class="empty">Nenhuma venda disponível.</div>'}
 function recibo(vendaId){const v=vendas().find(x=>String(x.id)===String(vendaId));if(!v)return;const doc={id:id(),tipo:'recibo',numero:next('REC'),criadoEm:iso(),data:today(),vendaId:v.id,venda:v};$('recPreview').innerHTML=`<h3>RECIBO ${esc(doc.numero)}</h3><p style="color:#6b7280">Venda ${esc(v.id||'')} • ${esc(v.data||today())} ${esc(v.hora||'')}</p><table><thead><tr><th>Item</th><th>Qtd.</th><th class="right">Total</th></tr></thead><tbody>${(v.itens||[]).map(i=>`<tr><td>${esc(i.nome||'Produto')}</td><td>${Number(i.qtd)||0}</td><td class="right">${money((Number(i.preco)||0)*(Number(i.qtd)||0))}</td></tr>`).join('')}</tbody></table><div class="total"><span>Desconto ${money(v.desconto||0)}<br>Pagamento: ${esc(v.formaPgto||'')}</span><strong>${money(v.total)}</strong></div><p style="text-align:center;margin-top:28px;font-weight:800">Recebemos o pagamento. Obrigado!</p>`;push(doc)}
 function next(prefix){const n=load().filter(x=>x.tipo==='encarte'&&prefix==='ENC'||x.tipo==='orcamento'&&prefix==='ORC'||x.tipo==='recibo'&&prefix==='REC').length+1;return `${prefix}-${new Date().getFullYear()}-${String(n).padStart(5,'0')}`}
 function push(doc){const a=load();a.unshift(doc);save(a);renderHistorico()}
 function renderHistorico(){const a=load();$('historico').innerHTML=a.length?a.slice(0,100).map(d=>`<div class="doc"><div><b>${esc(d.numero)} • ${esc(d.tipo)}</b><small>${esc(d.data)} • ${esc(d.cliente||d.venda?.operador||'')}</small></div><span class="tag">local</span></div>`).join(''):'<div class="empty">Nenhum documento gerado.</div>'}
 function print(){window.print()}
 function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tabpane').forEach(x=>x.classList.add('hidden'));$('tab-'+b.dataset.tab).classList.remove('hidden');if(b.dataset.tab==='recibo')renderVendas();if(b.dataset.tab==='historico')renderHistorico()})}
 function init(){const d=new Date();d.setDate(d.getDate()+7);$('orcValidade').value=d.toISOString().slice(0,10);$('encValidade').value=d.toISOString().slice(0,10);renderProducts();tabs();renderVendas();renderHistorico()}
 window.documentosService={init,gerarEncarte,salvarOrcamento,recibo,calcOrc,print};
 document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));
})();
